### ISSUE TITLE
release 1.0?

### ISSUE THREAD

**Issue by jjb** [thoughtbot/terrapin#25]
thanks for a great project!

Looks like there is a 1.0 tag from a couple months ago, but no release on rubygems.

**Comment by renchap** [comment]
A Rubygem release would be very welcome.

Pinging @jyurek as you seem to be the listed owner on Rubygems, as well as @brimatteng and @elisuh as you merged the last PRs

**Comment by mjankowski** [comment]
Resolved by https://github.com/thoughtbot/terrapin/pull/27
